spring.application.name=user-service


# MySQL connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/user_service?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pancake

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true